services:
    backend:
        container_name: study-buddy-backend-dev
        build:
            context: .
            dockerfile: backend/Dockerfile.dev
        command: poetry run python -m debugpy --listen 0.0.0.0:${DEBUG_PORT} --wait-for-client -m uvicorn app.main:app --host 0.0.0.0 --port  ${APP_PORT} --reload
        ports:
            - "${APP_PORT}:${APP_PORT}"
            - "${DEBUG_PORT}:${DEBUG_PORT}"
        volumes:
            - ./backend:/app
            - poetry-cache:/root/.cache/pypoetry
            - pip-cache:/root/.cache/pip
        env_file:
            - .env
        depends_on:
            - postgres
            - ollama

    postgres:
        image: postgres:15
        container_name: study-buddy-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: study_buddy
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    ollama:
        image: ollama/ollama
        container_name: ollama
        ports:
            - "11434:11434"
        volumes:
            - ollama-models:/root/.ollama

volumes:
    poetry-cache:
    pip-cache:
    ollama-models:
    postgres-data:
