repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        files: ^backend/

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        files: ^backend/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        args: [backend/app]
        files: ^backend/

  - repo: local
    hooks:
      - id: run-pytest
        name: Run Pytest
        entry: poetry run pytest backend/
        language: system
        types: [python]
        files: ^backend/